v1.1.0
eastgenomics/eggd_CANRISK_vcf pull request #16
Opened 2024-09-17 08:09 UTC by growland2

- Implement function to convert genotypes of uncertain genotypes to ref/ref (0/0), which can be applied optionally
    - #11
- Incorporate into the script conversion of variant representation to non-parsimonious form and conversion of uncalled variants to 0/0, which are currently done manually (see [Canrisk manual v3](https://cuhbioinformatics.atlassian.net/wiki/spaces/DV/pages/3073802241/Canrisk+Manual+v3)) 
    - #10
    - #14
 - Display genotype of PRS variants which failed depth and CNV overlap checks in their respective check files
    - #12 
    - #13  
 - Fix #15 
 - No longer output empty check files if no variants are found which fail the checks

2024-09-17 08:32 UTC, growland2 commented
Successful jobs
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/GqZYB684qZgzqv6G35g5v6Kx
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/GqZYj2j4qZgb7Bzjjj2JzG73
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/GqZYj304qZgYQfv4J3K53g1K (expected to fail)
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/GqZYj384qZgfF197Bbv75Xkj

2024-10-15 12:15 UTC, chrispyatt requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16)* status: all files reviewed, 9 unresolved discussions (waiting on @growland2)

___
*[`dxapp.json` line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9Bzn6PDTrdaU5aAY4d:-O9Bzn6PDTrdaU5aAY4e:byb92th) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/dxapp.json#L55)):*
> ```JSON
>       "name": "convert_gt_low_dp",
>       "label": "Convert the genotypes of low depth variants to 0/0",
>       "help": "whether the genotpyes of low depth (specified by the minimum depth input) variants are converted to 0/0. Cannot =true if exclude=true",
> ```

The exclude option doesn't exist any more (unless I'm just not seeing it) so the last sentence here can be removed
___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C06IkDBlta_p_4Rmr:-O9C06IkDBlta_p_4Rms:b-xpnddl) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L19)):*
> ```Markdown
> ## How does this app work?
> 
> Read depths of PRS variants are inspected and variants below the threshold are reported in a text output file. If no PRS variants with sub-threshold read depth exist, then no coverage check text file is outputted. Optionally, variants with sub-threshold read depth may have their genotype converted to 0/0 (default is `true`).  If required, it also checks the CNV segments file using `bcftools isec` to see if any PRS variants are in CNVs. Details of these variants are outputted in a text file, if no such variants are present then no text file is outputted. Moreover, PRS variants which occur in CNVs can optionally have their genotype converted to 0/0 (default is `true`). Lastly, PRS variants which were not able to be called (i.e. that have a GT = ./.) can optionally have their genotype be converted to 0/0 (default is `true`).
> ```

I feel like this section is almost paraphrasing the "What does the app do?" section (this was true before this PR too but maybe this is the opportunity to address it). Maybe we could describe the actual processes used by the app a bit? I.e. the app uses bcftools isec to do x and then bcftools filter to do y.
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C04gX6iLCR5YWbP4L:-O9C04gY0TjzCowOBPZp:b-tilxe8) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L24)):*
> ```Markdown
> 
> - a filtered VCF compatible with CANRISK
> - a text file listing excluded variants that are covered at less than input depth (default 20x)
> ```

if requested
___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C02d2B1qpUd5of59_:-O9C02d2B1qpUd5of59a:b-tilxe8) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L25)):*
> ```Markdown
> - a filtered VCF compatible with CANRISK
> - a text file listing excluded variants that are covered at less than input depth (default 20x)
> - a text file listing PRS positions that are affected by an overlapping CNV
> ```

if requested
___
*[`src/eggd_CANRISK_vcf.sh` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9F4cawE2GpdTjzIXUw:-O9F4cawE2GpdTjzIXUx:byndvl8) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L13)):*
> ```Shell
> 
>     # make vcf containing non-selected variants
>     bcftools isec "$original_vcf" -T ^"$regions_file" -w1 -o intersect_removed.vcf
> ```

Can we add a little comment to say that the ^ grabs everything that doesn't match the regions file (sorry if this is obvious to everyone else but it took me a while to work out)
___
*[`src/eggd_CANRISK_vcf.sh` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9EKBcF1cV0JO_Yvnu1:-O9EKBcG6M7Xjtx7laEm:b-wwz0g4) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L54)):*
> ```Shell
>         echo "ERROR: no segments file was provided via segments_vcf but convert_gt_cnv was set to true"
>         exit 1
>     fi
> ```

note to self - are there any other input checks that should be done?
___
*[`src/eggd_CANRISK_vcf.sh` line 131 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9Eolp06vJtyyo2oXXa:-O9Eolp06vJtyyo2oXXb:b-8d3wft) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L131)):*
> ```Shell
>         fi
>     else
>         echo "No segment provided, therefore no CNV checking was performed for this sample."
> ```

"No segment vcf"?
___
*[`src/eggd_CANRISK_vcf.sh` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9EzoJ63W8fQjY-N9jq:-O9EzoJ63W8fQjY-N9jr:bv1k0bp) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L138)):*
> ```Shell
>     if $convert_gt_no_call; then
>         mark-section "Converting genotype of uncalled PRS variants to 0/0"
>         sed -i 's/\.\/\./0\/0/g' "$sample_name"_canrisk_PRS.vcf
> ```

Maybe it would be better to use convert_gt again for this, purely for the additional sense checking present in the function.
___
*[`src/eggd_CANRISK_vcf.sh` line 141 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9F5g0xAVevFLBp4LTj:-O9F5g0xAVevFLBp4LTk:buanpzg) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L141)):*
> ```Shell
>     fi
> 
>     sed -i 's/4\t84370124\trs10718573\tTA\tT/4\t84370124\trs10718573\tTAA\tTA/' "$sample_name"_canrisk_PRS.vcf
> ```

comment to say why we're changing these variants please


<!-- Sent from Reviewable.io -->

2024-10-16 14:55 UTC, growland2 reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @chrispyatt)

___
*[`dxapp.json` line 55 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9Bzn6PDTrdaU5aAY4d:-O9JTkitAWquBm1AmF7t:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/dxapp.json#L55)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

The exclude option doesn't exist any more (unless I'm just not seeing it) so the last sentence here can be removed
</blockquote></details>

Done.
___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C06IkDBlta_p_4Rmr:-O9JWrlq8EAhUP7UGe78:blkzfju) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L19)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

I feel like this section is almost paraphrasing the "What does the app do?" section (this was true before this PR too but maybe this is the opportunity to address it). Maybe we could describe the actual processes used by the app a bit? I.e. the app uses bcftools isec to do x and then bcftools filter to do y.
</blockquote></details>

Agree, I have removed what was in "What does the app do?" and replaced it with the contents of "How does this app work?" and I have re-written  "How does this app work?" providing more details of the commands used. 
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C04gX6iLCR5YWbP4L:-O9JpRK8BtSNxRe2QKlG:b-3u3v22) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L24)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

if requested
</blockquote></details>

Text files are always written if they can be (i.e. if there are variants with low depth or which overlap with CNVs check files are written) rather than requested - I have added this in and removed reference to excluded variants as we no longer exclude variants.
___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9C02d2B1qpUd5of59_:-O9JrYfoEo9d3Ijj_RdH:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/README.md#L25)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

if requested
</blockquote></details>

Done.
___
*[`src/eggd_CANRISK_vcf.sh` line 13 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9F4cawE2GpdTjzIXUw:-O9JfZES5v8dXh6VqoEe:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L13)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Can we add a little comment to say that the ^ grabs everything that doesn't match the regions file (sorry if this is obvious to everyone else but it took me a while to work out)
</blockquote></details>

Done.
___
*[`src/eggd_CANRISK_vcf.sh` line 131 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9Eolp06vJtyyo2oXXa:-O9Jsf7Q2RfiylVFo48a:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L131)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

"No segment vcf"?
</blockquote></details>

Done.
___
*[`src/eggd_CANRISK_vcf.sh` line 138 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9EzoJ63W8fQjY-N9jq:-O9Jsg575qD4_2VgfOUj:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L138)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

Maybe it would be better to use convert_gt again for this, purely for the additional sense checking present in the function.
</blockquote></details>

Done.
___
*[`src/eggd_CANRISK_vcf.sh` line 141 at r1](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16#-O9F5g0xAVevFLBp4LTj:-O9Jt96VA4M-ld-QIfKn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_CANRISK_vcf/blob/ced6b9b3e48aa55856e171a1bbe11e0277f53cf2/src/eggd_CANRISK_vcf.sh#L141)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

comment to say why we're changing these variants please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-16 14:57 UTC, growland2 commented
App rebuilt post-changes and re-tested.

```
dx run app-GqBkX2Q4zXGYbVvYyy9BpjvK \
-idepth=500 \
-isample_vcf=file-Gv7p2k04qZgXp6X7q5xK3Z1v \
-isegments_vcf=file-GqX0vFj4qZgXPVF629P8Bvq5 \
--name="test_convert_low_dp_and_cnv_overlaps_and_uncalled_vars" -y

dx run app-GqBkX2Q4zXGYbVvYyy9BpjvK \
-isample_vcf=file-Gv7p2k04qZgXp6X7q5xK3Z1v \
--name="test_input_conflict_no_segments_file_provided_and_convert_cnv_requested" -y


dx run app-GqBkX2Q4zXGYbVvYyy9BpjvK \
-idepth=500 \
-isample_vcf=file-Gv7p2k04qZgXp6X7q5xK3Z1v \
-isegments_vcf=file-GqX0vFj4qZgXPVF629P8Bvq5 \
-iconvert_gt_cnv=false \
-iconvert_gt_low_dp=false \
-iconvert_gt_no_call=false \
--name="test_no_dp_cnv_or_uncalled_conversion" -y
```

Links to jobs:
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/Gv7vQ304qZggf7FVv5zBzkqg
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/Gv7vQ2j4qZgX8Z1XZB00jg0P
https://platform.dnanexus.com/panx/projects/GqBkBFj4qZgbBbZy86yBQ10j/monitor/job/Gv7vQ384qZgjVbq1GFZGyg5z

2024-10-17 13:50 UTC, chrispyatt approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)



<!-- Sent from Reviewable.io -->

2024-10-17 13:50 UTC, chrispyatt approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_CANRISK_vcf/16)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @growland2)



<!-- Sent from Reviewable.io -->

2024-10-17 13:50 UTC, merged